### ISSUE TITLE
Maven Non-Compile

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TF-LibsDisguises#4]
Currently one of the dependencies within the Pom is unable to be resolved, and as a result the plugin cannot compile. This is blocking other merges on the main TFM Project.

**Comment by lemonsked** [comment]
Which one, @Wild1145?

**Comment by Wild1145** [comment]
It appears Maven cannot resolve the Proticol lib dependency.

**Comment by lemonsked** [comment]
fixed in [7c40029](https://github.com/TotalFreedom/TF-LibsDisguises/commit/7f86871772fb8204ecf6720ae6840c7876c40ae3) @Wild1145

**Comment by Wild1145** [comment]
Compilation is still failing: https://jitpack.io/com/github/TotalFreedom/TF-LibsDisguises/914c7289d5/build.log

**Comment by Wild1145** [comment]
So I have checked, the repo that is being used for Proticol lib does not appear to be functional. I am currently testing another option to resolve the issues as this is now blocking TFM Maven's branch from building. If it works I'll raise a PR to resolve this issue.

**Comment by lemonsked** [comment]
Compiles, ProtocolLib repo is now functional.

**Comment by Wild1145** [comment]
This continues to be an issue.
